# Generated by Django 4.0.6 on 2022-07-05 09:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import wagtail.blocks
import wagtail.documents.blocks
import wagtail.fields
import wagtail.images.blocks
import wagtail.search.index


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0024_index_image_file_hash'),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
            ],
            options={
                'verbose_name': 'Gallerie',
            },
        ),
        migrations.AlterModelOptions(
            name='homepage',
            options={'verbose_name': "Page d'Accueil"},
        ),
        migrations.AddField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('body', wagtail.fields.StreamField([('heading', wagtail.blocks.CharBlock(form_classname='full title', label='Titre')), ('richtext', wagtail.blocks.RichTextBlock(features=['bold', 'italic', 'link', 'ol', 'ul'], label='Paragraphe')), ('image', wagtail.images.blocks.ImageChooserBlock(label='Image')), ('pdf', wagtail.documents.blocks.DocumentChooserBlock(label='PDF'))], blank=True, help_text='Corps de la page', use_json_field=None, verbose_name='Contenu')),
                ('name', models.CharField(max_length=100, verbose_name="Nom de l'oeuvre")),
                ('slug', models.SlugField(blank=True, default='', max_length=100, unique=True, verbose_name='Slug (URL de la ressource)')),
                ('short_description', models.CharField(max_length=510, verbose_name='Description courte')),
                ('galleries', models.ManyToManyField(blank=True, related_name='artworks', to='home.gallery', verbose_name='Galleries')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Image principale')),
            ],
            options={
                'verbose_name': 'Oeuvre',
                'verbose_name_plural': 'Oeuvres',
                'ordering': ['-created'],
            },
            bases=(wagtail.search.index.Indexed, models.Model),
        ),
    ]
