# Generated by Django 4.0.6 on 2022-10-26 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PresentationPage',
        ),
    ]
