# Generated by Django 4.0.6 on 2022-10-26 13:40

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_delete_presentationpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workexperiencepage',
            name='parcours_block_data',
            field=wagtail.fields.StreamField([('chapters', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(label='Titre')), ('intro', wagtail.blocks.CharBlock(label='Introduction', required=False)), ('steps', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('date', wagtail.blocks.CharBlock(label='Date', required=False)), ('richtext', wagtail.blocks.RichTextBlock(features=['bold', 'italic', 'link', 'ol', 'ul'], label='Description'))], label='Les différentes étapes de ton parcours', label_format='{date}'), label='Etapes'))], label='Parties de ton parcours', label_format='{title}'))], blank=True, use_json_field=True, verbose_name='Parcours'),
        ),
    ]
