# Generated by Django 4.0.6 on 2022-07-27 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_artworkspage_gallery_workexperiencepage_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workexperiencepage',
            options={'verbose_name': 'Page du parcours'},
        ),
    ]
