# Generated by Django 4.0.5 on 2022-06-22 14:27

from django.db import migrations, models
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='title_home',
            field=models.CharField(blank=True, help_text="titre page d'accueil", max_length=68, verbose_name='Titre'),
        ),
    ]
