# Generated by Django 4.0.6 on 2022-07-27 13:28

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_workexperiencepage_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workexperiencepage',
            name='parcours_block_data',
            field=wagtail.fields.StreamField([('chapters', wagtail.blocks.StructBlock([('subtitle', wagtail.blocks.CharBlock(label='Sous titre')), ('steps', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('date', wagtail.blocks.CharBlock(blank=True, label='Date', null=True)), ('richtext', wagtail.blocks.RichTextBlock(features=['bold', 'italic', 'link', 'ol', 'ul'], label='Description'))], label='Les différentes étapes de ton parcours', label_format='{date}')))], label='Parties de ton parcours', label_format='{subtitle}'))], blank=True, use_json_field=None, verbose_name='Parcours'),
        ),
    ]
