# Generated by Django 4.0.5 on 2022-06-22 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage_body_homepage_title_home'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='title_home',
        ),
    ]
