# Generated by Django 4.0.6 on 2022-07-06 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20220705_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='color',
            field=models.CharField(choices=[('gallery-blue', 'Bleue'), ('gallery-purpule', 'Violet'), ('gallery-orange', 'Orange'), ('gallery-cyan', 'Cyan'), ('gallery-green', 'Vert'), ('gallery-yellow', 'Jaune'), ('gallery-red', 'Rouge')], default='gallery-blue', help_text='Choisir la couleur de la galerie', max_length=32),
        ),
    ]
