# Generated by Django 4.0.6 on 2022-07-29 12:58

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_homepage_body_homepage_artist_body_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageArtworks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artwork', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.artwork', verbose_name='Oeuvre')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='artworks_highlight', to='home.homepage')),
            ],
            options={
                'unique_together': {('page', 'artwork')},
            },
        ),
    ]
