# Generated by Django 4.0.6 on 2022-07-05 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_gallery_alter_homepage_options_artwork'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=100, unique=True, verbose_name='Slug (URL de la ressource)'),
        ),
    ]
