# Generated by Django 4.0.6 on 2022-07-29 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_homepage_artworks_highlight_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='artist_name',
            field=models.CharField(blank=True, help_text="Si ce champs est vide alors cette partie ne s'affichera pas dans l'Accueil", max_length=100, null=True, verbose_name='Nom'),
        ),
    ]
