# Generated by Django 4.0.6 on 2022-07-29 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_homepage_artist_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepageartworks',
            name='artwork',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artworks_highlight', to='home.artwork', verbose_name='Oeuvre'),
        ),
    ]
