# Generated by Django 4.0.6 on 2022-07-25 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0024_index_image_file_hash'),
        ('home', '0008_bannersetting'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bannersetting',
            options={'verbose_name': 'Banière-image'},
        ),
        migrations.AlterField(
            model_name='bannersetting',
            name='navbar_banner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Image'),
        ),
    ]
