# Generated by Django 4.0.6 on 2022-07-25 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_bannersetting_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artworkspage',
            options={'verbose_name': 'Page des galeries', 'verbose_name_plural': 'Pages des galeries'},
        ),
        migrations.AlterField(
            model_name='artwork',
            name='galleries',
            field=models.ManyToManyField(blank=True, related_name='artworks', to='home.gallery', verbose_name='Galeries'),
        ),
    ]
