# Generated by Django 4.0.6 on 2022-08-25 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_homepageartworks_artwork'),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendlySite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('link', models.CharField(max_length=255, verbose_name="Nom de l'oeuvre")),
            ],
            options={
                'verbose_name': 'Site ami',
                'verbose_name_plural': 'Sites amis',
            },
        ),
    ]
