# Generated by Django 4.0.6 on 2022-07-25 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_artworkspage_options_alter_artwork_galleries'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name': 'Galerie'},
        ),
    ]
