# Generated by Django 4.0.6 on 2022-08-25 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_friendlysite'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferenceSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('link', models.CharField(max_length=255, verbose_name='Lien')),
            ],
            options={
                'verbose_name': 'Site référence',
                'verbose_name_plural': 'Sites références',
            },
        ),
        migrations.AlterField(
            model_name='friendlysite',
            name='link',
            field=models.CharField(max_length=255, verbose_name='Lien'),
        ),
    ]
