# Generated by Django 4.0.6 on 2022-08-25 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_referencesite_alter_friendlysite_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendlysite',
            name='display',
            field=models.BooleanField(default=True, verbose_name='Afficher'),
        ),
        migrations.AddField(
            model_name='referencesite',
            name='display',
            field=models.BooleanField(default=True, verbose_name='Afficher'),
        ),
    ]
