# Generated by Django 4.0.6 on 2022-10-05 12:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import wagtail.blocks
import wagtail.documents.blocks
import wagtail.fields
import wagtail.images.blocks
import wagtail.search.index


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0024_index_image_file_hash'),
        ('wagtaildocs', '0012_uploadeddocument'),
        ('home', '0012_friendlysite_display_referencesite_display'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Exemple: Poème, Extrait de catalogue', max_length=100, verbose_name='Nom')),
            ],
            options={
                'verbose_name': "Type d'article",
            },
        ),
        migrations.AlterField(
            model_name='artwork',
            name='body',
            field=wagtail.fields.StreamField([('heading', wagtail.blocks.CharBlock(form_classname='full title', label='Titre')), ('richtext', wagtail.blocks.RichTextBlock(features=['bold', 'italic', 'link', 'ol', 'ul'], label='Paragraphe')), ('image', wagtail.images.blocks.ImageChooserBlock(label='Image')), ('pdf', wagtail.documents.blocks.DocumentChooserBlock(label='PDF'))], blank=True, help_text='Corps de la page', use_json_field=True, verbose_name='Contenu'),
        ),
        migrations.AlterField(
            model_name='workexperiencepage',
            name='parcours_block_data',
            field=wagtail.fields.StreamField([('chapters', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(label='Titre')), ('steps', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('date', wagtail.blocks.CharBlock(label='Date', required=False)), ('richtext', wagtail.blocks.RichTextBlock(features=['bold', 'italic', 'link', 'ol', 'ul'], label='Description'))], label='Les différentes étapes de ton parcours', label_format='{date}'), label='Etapes'))], label='Parties de ton parcours', label_format='{title}'))], blank=True, use_json_field=True, verbose_name='Parcours'),
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('body', wagtail.fields.StreamField([('heading', wagtail.blocks.CharBlock(form_classname='full title', label='Titre')), ('richtext', wagtail.blocks.RichTextBlock(features=['bold', 'italic', 'link', 'ol', 'ul'], label='Paragraphe')), ('image', wagtail.images.blocks.ImageChooserBlock(label='Image')), ('pdf', wagtail.documents.blocks.DocumentChooserBlock(label='PDF'))], blank=True, help_text='Corps de la page', use_json_field=True, verbose_name='Contenu')),
                ('name', models.CharField(max_length=100, verbose_name="Nom de l'article")),
                ('slug', models.SlugField(blank=True, default='', max_length=100, unique=True, verbose_name="Slug (URL de l'article)")),
                ('short_description', models.CharField(max_length=256, verbose_name='Description courte')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Image principale')),
                ('pdf', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.document', verbose_name='PDF')),
                ('types', models.ManyToManyField(blank=True, related_name='articles', to='home.articletype', verbose_name="Types d'article")),
            ],
            options={
                'verbose_name': 'Oeuvre',
                'verbose_name_plural': 'Oeuvres',
                'ordering': ['-created'],
            },
            bases=(wagtail.search.index.Indexed, models.Model),
        ),
    ]
