# Generated by Django 4.0.6 on 2022-07-26 17:10

from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.contrib.routable_page.models
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0069_log_entry_jsonfield'),
        ('home', '0012_presentationpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkExperiencePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.fields.RichTextField(blank=True, null=True, verbose_name='Introduction de la page parcours')),
                ('parcours_block_data', wagtail.fields.StreamField([('chapters', wagtail.blocks.StructBlock([('subtitle', wagtail.blocks.CharBlock(label='Sous titre')), ('steps', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('date', wagtail.blocks.CharBlock(label='Date')), ('richtext', wagtail.blocks.RichTextBlock(features=['bold', 'italic', 'link', 'ol', 'ul'], label='Description'))], label='Les différentes étapes de ton parcours', label_format='{date}')))], label='Parties de ton parcours', label_format='{subtitle}'))], blank=True, use_json_field=None, verbose_name='Membres du Comité - contenu')),
            ],
            options={
                'verbose_name': 'Page de presentation',
            },
            bases=(wagtail.contrib.routable_page.models.RoutablePageMixin, 'wagtailcore.page'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.RichTextField(blank=True, null=True, verbose_name="Contenu de la page d'accueil"),
        ),
        migrations.AlterField(
            model_name='presentationpage',
            name='body',
            field=wagtail.fields.RichTextField(blank=True, null=True, verbose_name='Contenu de la page de présentation'),
        ),
    ]
