# Generated by Django 4.0.6 on 2022-10-05 18:06

from django.db import migrations
import wagtail.blocks
import wagtail.documents.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_articlespage_nav_name_artworkspage_nav_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='body',
            field=wagtail.fields.StreamField([('heading', wagtail.blocks.CharBlock(form_classname='full title', label='Titre')), ('richtext', wagtail.blocks.RichTextBlock(label='Paragraphe')), ('image', wagtail.images.blocks.ImageChooserBlock(label='Image')), ('pdf', wagtail.documents.blocks.DocumentChooserBlock(label='PDF'))], blank=True, help_text='Corps de la page', use_json_field=True, verbose_name='Contenu'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='body',
            field=wagtail.fields.StreamField([('heading', wagtail.blocks.CharBlock(form_classname='full title', label='Titre')), ('richtext', wagtail.blocks.RichTextBlock(label='Paragraphe')), ('image', wagtail.images.blocks.ImageChooserBlock(label='Image')), ('pdf', wagtail.documents.blocks.DocumentChooserBlock(label='PDF'))], blank=True, help_text='Corps de la page', use_json_field=True, verbose_name='Contenu'),
        ),
    ]
